# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c3cf05031c6b8bd2a75f3f72e153e0512fe4ffba5636c4f8a1713dfa3c43cd09e506d43d7bf5109c597d168b8fa88a086a5653c66cbad44f00011d228981cfb

test:
  secret_key_base: 2ee77b32a0cfd2f22f2beeb583e5128ea071c6bd3cbd6a960f7395a1233a114dac30cd72ea8008b3cfafaccd0b1592191cb41ee1f6ad1765c178df6db0d1ed8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
